### ISSUE TITLE
Trying to set the end color of a gradient causes a crash

### ISSUE THREAD

**Issue by arkdae** [deadw00d/AROS#101]
I think I wanted to provide a pull request, but I've never contributed to a GitHub/GitLab project before so I don't know how to do so. The fix is really simple, though.

If you do this: open System -> Prefs -> Zune then select window from the left hand list, click on the large window button on the right, select the gradient tab in the new popup window, and click on the darker color button ... you get a crash. The lighter color button works. A back trace shows that the window title is neither a NULL pointer, nor pointing to a valid location. It reports being unable to get the string length at memory address 0x20.

I totally do not understand the code constructs involved, but I just compared the code for creating the start color window to the code for the end color window and made the latter match the former:

```
diff --git a/workbench/libs/muimaster/classes/imageadjust.c b/workbench/libs/muimaster/classes/imageadjust.c
index 6e4104d1c2..ed0dd57b65 100644
--- a/workbench/libs/muimaster/classes/imageadjust.c
+++ b/workbench/libs/muimaster/classes/imageadjust.c
@@ -634,7 +634,7 @@ IPTR Imageadjust__OM_NEW(struct IClass *cl, Object *obj, struct opSet *msg)
                     End)),
                 Child, (IPTR) (gradient_end_poppen =
                     (Object *) PoppenObject,
-                    MUIA_Window_Title, (IPTR) MSG_IMAGEADJUST_END_PEN,
+                    MUIA_Window_Title, (IPTR) _(MSG_IMAGEADJUST_END_PEN),
                     MUIA_Pendisplay_Spec, (IPTR) "r55555555,55555555,55555555",
                     End),
                 End,

```
With this, no more crash.

**Comment by arkdae** [comment]
Unfortunately, now that I have gotten passed the crash, although the gradient looks nice in the Zune prefs, it is all messed up as window backgrounds.
![Selection_015](https://user-images.githubusercontent.com/4141632/236352322-85608a8c-f8e6-4861-84cd-dd7612535d31.png)

**Comment by arkdae** [comment]
By compiling out case 0 of zune_gradient_drawfast() vertical window gradients work. I assume it exists to be faster than the general FillPixelArrayGradient(). Looking closely at both cases 0 and 90, I can see no obvious difference which should cause this graphical error. Further examination of TrueDitherH() and TrueDitherV() also yielded no obvious error.

**Comment by deadw00d** [comment]
Hello,

Thanks for the report and fix. Can you tell me which branch are you working on? master (64-bit) or alt-abiv0 (32-bit)?

**Comment by arkdae** [comment]
I am on the alt-abvi0 branch.

I'm getting the idea that perhaps gradients weren't meant for window backgrounds. Even working around the graphical bug in the window above, horizontal gradients use only a very small portion of the beginning of the gradient within the window, and at other angles there is odd banding instead of smooth color transitions. Gradients look much better in buttons and other gadgets.

Which is odd, because I've seen plenty of screenshots in forums which seem to have color gradients in the backgrounds of windows. Maybe they are using bitmaps there instead.

**Comment by arkdae** [comment]
MUI 5.0 doesn't have gradient angles. But from what I can see the horizontal and vertical gradients look correct in everything I tried.

**Comment by deadw00d** [comment]
Ok, are you interested in investigating this gradient issue further? If you need support, I could help out with questions about AROS internals / builds process.

**Comment by arkdae** [comment]
Thanks for your support. I think what we can do is close out this bug report.

What I'll do is if I work on it I can open a new issue. I think as far as things go this isn't super important. My current theory is that perhaps the x1, y1, x2, y2 values being passed in to the gradient function aren't quite right for window backgrounds. It seems like the vertical gradient is too tight and the horizontal gradient is too relaxed.
