### ISSUE TITLE
Compiling Scalos

### ISSUE THREAD

**Issue by markusbkk** [deadw00d/AROS#106]
Curious. Is there any documentation for compiling Scalos for AxRuntime?
I downloaded the source code from Sourceforge and ran `make` but that's obviously not enough and I'm not sure if there's not a newer version or if you modified the Scalos source code yourself in some way.

Would love to create a little distro based on [distri](https://github.com/distr1/distri).

**Comment by deadw00d** [comment]
Hello,

Scalos "ported" to AxRuntime is available in my contrib (https://github.com/deadw00d/contrib) repository. In order to build it, you first needs to build AxRuntime itself. Please follow these instructions: https://github.com/deadw00d/AROS/blob/alt-runtime/INSTALL.md.

**Comment by markusbkk** [comment]
> Hello,
> 
> Scalos "ported" to AxRuntime is available in my contrib (https://github.com/deadw00d/contrib) repository. In order to build it, you first needs to build AxRuntime itself. Please follow these instructions: https://github.com/deadw00d/AROS/blob/alt-runtime/INSTALL.md.

Awesome! Thanks for the quick response.
Gonna check it out right away.

Compiled AxRuntime yesterday night but didn't know where to find the proper Scalos source.

Am I right to assume that AREXX ports work as well?

**Comment by deadw00d** [comment]
On the AREXX port question, I don't really know. Just to be clear, Scalos is pre-alpha stage now. It "works" now if you know what not to click, so don't expect too much

With regards to "contrib", be sure to place the repository inside of AROS directory and be sure to checkout alt-runtime branch in it.

**Comment by markusbkk** [comment]
> On the AREXX port question, I don't really know. Just to be clear, Scalos is pre-alpha stage now. It "works" now if you know what not to click, so don't expect too much
> 

Was thinking more of AREXX ports in general. Will experiment with it later, from AROS Shell. Would be quite amazing if that part works properly without even needing any kernel support.

> With regards to "contrib", be sure to place the repository inside of AROS directory and be sure to checkout alt-runtime branch in it.

So the AROS working directory that belongs to this repository? I just moved it there but it's still complaining about missing
files and directory.

I'll have to go to bed for a bed. Will investigate when I get back up. At least I know what source to use now. Thanks.

**Comment by deadw00d** [comment]
Yes, the structure you should have (assuming you used my scripts to build) is:

alt-runtimelinux-x86_64-d
AROS
toolchain-alt-runtimelinux-x86_64

where AROS is the git repository for "core". Now checkout contrib (and alt-runtime branch) and place it as AROS/contrib

the cd into alt-runtimelinux-x86_64-d and from there issue make contrib-scalos and if all goes well, you should have the binary.

(if things don't work, first follow the instructions for building AxRuntime and the last part about building Wanderer to validate)

**Comment by markusbkk** [comment]
> Yes, the structure you should have (assuming you used my scripts to build) is:
> 
> alt-runtimelinux-x86_64-d AROS toolchain-alt-runtimelinux-x86_64
> 
> where AROS is the git repository for "core". Now checkout contrib (and alt-runtime branch) and place it as AROS/contrib
> 
> the cd into alt-runtimelinux-x86_64-d and from there issue make contrib-scalos and if all goes well, you should have the binary.
> 
> (if things don't work, first follow the instructions for building AxRuntime and the last part about building Wanderer to validate)

Thanks! `make contrib-scalos` worked. Unfortunately, I'm on ChromeOS right now so the GUI doesn't work correctly. Will test it in a proper GNU/Linux distro tomorrow.

**Comment by deadw00d** [comment]
FYI I made binary of Intuition and needed integration scripts available here (https://github.com/deadw00d/AROS/discussions/83) if you are interested.

**Comment by markusbkk** [comment]
> FYI I made binary of Intuition and needed integration scripts available here (#83) if you are interested.

I'd prefer compiling the source myself but thanks for the heads-up.

Slightly different issue. I'm trying to compile the SDK but whenever I run `make sdk` from inside `alt-runtimelinux-x86_64-d` I receive the following error.

>[MMAKE] make --no-print-directory TOP=/home/username/libaxrt/alt-runtimelinux-x86_64-d SRCDIR=/home/username/libaxrt/AROS CURDIR=arch/x86_64-all/crt TARGET=compiler-m-x86_64 --file=mmakefile compiler-m-x86_64 failed: 512
[MMAKE] Error: Error while running make in arch/x86_64-all/crt: No such file or directory
make[1]: *** [Makefile:357: linklibs-libatomic] Error 10
make: *** [Makefile:179: crosstools] Error 2

PS: Should I move any further inquiries to the discussion thread you linked, so you can close this issue?

**Comment by deadw00d** [comment]
With regards to compiling Scalos, this issue is ok to continue.

The sdk target might not work. Can you explain what you want to achieve? Do you want to build the .deb package for SDK & libs (like the one to be downloaded from here: https://axrt.org/downloads)?

**Comment by markusbkk** [comment]
> The sdk target might not work. Can you explain what you want to achieve? Do you want to build the .deb package for SDK & libs (like the one to be downloaded from here: https://axrt.org/downloads)?

Basically. Or just copying the files to the proper paths. But I just realized that's not what it's doing.
Ended up extracting the files from the .deb. The example builds now, minus the debug flags patchelf-debug adds (not really tragic, but I know where to find your patchelf project in case I need it).

**Comment by deadw00d** [comment]
Ok, FYI the target to build the deb packages is 'runtime-package-deb' and the SDK physically sits in alt-runtimelinux-x86_64-d/bin/runtimelinux-x86_64/AROS/Development/

**Comment by deadw00d** [comment]
FYI, if you have no more specifics questions about compiling Scalos, I will close this item.

**Comment by markusbkk** [comment]
> FYI, if you have no more specifics questions about compiling Scalos, I will close this item.

Sure. Thanks.
