### ISSUE TITLE
Compiling error zlib 1.2.13

### ISSUE THREAD

**Issue by chrisripp** [deadw00d/AROS#124]
Hello, Can you update your script. Zlib 1.2.13 Can not be downloaded by the script. Thanks you.

**Comment by deadw00d** [comment]
Which branch are you building? Master?

**Comment by chrisripp** [comment]
I wanted to compile Aros on Ubuntu 20.04. When I run rebuild.sh, (toolchain-core-x86_64), the compilation blocks downloading zlib. I think the zlib link is no longer valid. I tried to paste zlib1.2.3 into Aros/portssources. But this time the script blocks:
"fetching zlib-1.2.13..."
"fetch.sh: waiting for process with PID: 130869 to finish downloading..."
the compilation stays there. Screenshooot here https://ibb.co/m5gKDPb

**Comment by deadw00d** [comment]
Ok, for some reason download of zlib failed in your case and you have a "temporary" file stored in portsources.
First, see if you have access https://zlib.net/fossils/. If you can, then there should be no problem. Next go to portsources, show "hidden" files and delete everything related to zlib. Now if you run build again, zlib should download. If not, then delete the complete portsources, create it empty and then just copy zlib-1.2.13.tar.gz to it and run build again.

**Comment by chrisripp** [comment]
Thanks you, I deleted  .fetchzlib.
Zlib passed, 
Compiling .....

**Comment by deadw00d** [comment]
Good to know, thanks!
On another topic, do you plan porting some software to 64-bit or only wanted to setup local build?

**Comment by chrisripp** [comment]
I am on an Amiga project (cdlive-custum+install on ssd, usb hdd...), my goal is to launch Aros (bootstrap) on ubuntu at startup. From Aros, I want to create menus, demos, magazines, mods. I haven't thought about the menus yet. I already have to build my ISO with Aros. To make an Aros bootstrap x64, do you have to choose choice 1 or 2 in rebuild.sh? Then I find where the bootstrap binary? I redo a compilation with choice 2 (debug)

**Comment by chrisripp** [comment]
Yea compilation ok
screenshoot https://ibb.co/fHS7WYq

**Comment by deadw00d** [comment]
If I understand you correctly, you want to write Amiga software but run in under linux via AROS? If so, there might be a better solution for you: AxRuntime https://github.com/deadw00d/AROS/tree/alt-runtime

It allows writing software using Amiga API but after compiling you get a linux binary that just needs the runtime installed on linux side - no full AROS.

**Comment by deadw00d** [comment]
Alternatively you can download pre-built packages from https://axrt.org/downloads
