### ISSUE TITLE
BoingIconBar has hardcode fonts

### ISSUE THREAD

**Issue by aGGre55or** [deadw00d/AROS#28]
There is no way to change the built-in font assignments and the user has nowhere to find out what these fonts are.
In [AROS/workbench/tools/BoingIconBar/iconbar.c](https://github.com/aros-development-team/AROS/blob/faebdbeca09fd33673af6b5ca2f3fb1e2c82830d/workbench/tools/BoingIconBar/iconbar.c)

static struct TextFont *TF_XHelvetica;
static struct TextAttr XHelvetica = {"arial.font", 9, 0, FPF_DISKFONT};
static struct TextAttr Topaz8 = {"topaz.font",8,0,FPF_ROMFONT};

On practice, in AROS-20170402 this leads to the following:
![boingiconbar](https://user-images.githubusercontent.com/3582394/102139946-98c0db80-3e6f-11eb-9bf2-2e0cbcde2c2a.png)

Here the developer had to add an argument to specify a custom font, but he didn't.. :(

**Comment by deadw00d** [comment]
Fixed upstream: https://github.com/aros-development-team/AROS/commit/b53fd9c96c21df7953e3b5cf91b45421a202dd28

**Comment by aGGre55or** [comment]
It works! Thank you!
![AROS_BB_fonts](https://user-images.githubusercontent.com/3582394/107741509-59ebbc80-6d1e-11eb-8969-87fd42b64fdc.png)
