### ISSUE TITLE
ReadArgs / argv / argc don't seem to work

### ISSUE THREAD

**Issue by sodero** [deadw00d/AROS#3]
Only argv[0] seems to work, argc == 1 no matter the number of arguments. Also, ReadArgs(...) return NULL. Steps to reproduce:

- git clone https://github.com/sodero/InstallerLG.git
- cd build
- make -f Makefile.axrt
- ./Installer axrt.script

**Comment by sodero** [comment]
I forgot, use the axrt_test branch...

**Comment by deadw00d** [comment]
Thanks for reporting. This is indeed missing functionality. I'm now looking into network support. I will look into this next.

**Comment by deadw00d** [comment]
Implemented in 9010d0cd2d1fdc8c72e4e6691b3d1a8430c76582
