### ISSUE TITLE
Wanderer Prefs doesn't work with IFF/ILBM

### ISSUE THREAD

**Issue by aGGre55or** [deadw00d/AROS#36]
Wanderer doesn't install files in IFF/ILBM format on the desktop.
This error is present in AROS-20170402-3 and other AROS distros like AROS One.

[Patterns.zip](https://github.com/deadw00d/AROS/files/5746474/Patterns.zip)
![bug_wanderer_iff](https://user-images.githubusercontent.com/3582394/103201802-deff4b80-4901-11eb-8245-4a0930e34092.png)

**Comment by deadw00d** [comment]
Confirmed to be fixed: https://arosworld.org/infusions/forum/viewthread.php?action=reply&forum_id=4&thread_id=1142&post_id=2670&quote=2670
