### ISSUE TITLE
fread(a, b, 0, c) bug

### ISSUE THREAD

**Issue by steffengutmann** [deadw00d/AROS#52]
A call to fread(buffer, size, 0, file) sets the EOF flag of the file descriptor.  This is because of how AROS/compiler/posixc/fread.c (https://github.com/aros-development-team/AROS/blob/master/compiler/posixc/fread.c) is implemented:

Code: [Select]
   
    else if (cnt == 0 || cnt < nblocks)
    {
	stream->flags |= __POSIXC_STDIO_EOF;
    }

The fix would be to change the condition to "else if (cnt < nblocks)" only, or do an early return 0 similar to how it is done in AROS/compiler/stdc/fread.c

Of course, it is easy to work around this by simply not calling fread when there is nothing to be read.

Attached is a test case including how to reproduce and the output on Linux and AROS.

[fread.c.txt](https://github.com/deadw00d/AROS/files/7790483/fread.c.txt)

**Comment by deadw00d** [comment]
@steffengutmann Do you need fix for this ported to ABIv0 as well?

**Comment by steffengutmann** [comment]
Absolutely.

But please note that I am not developing for AROS, just making my SW available for AROS.  And I have already worked-around this problem in my SW.  But I would not be surprised if other SW also runs into this same bug.

**Comment by deadw00d** [comment]
Fixed in 1d67ef55564dffa603f24808ebbaf9974dadfc07
