### ISSUE TITLE
Incompatibility: MUIM_HandleEvent when using MUIM_Window_AddEventHandler

### ISSUE THREAD

**Issue by steffengutmann** [deadw00d/AROS#53]
On Classic MUI one can install an event handler using MUIM_Window_AddEventHandler in MUIM_Window_Setup and use the window object as the object receiving the events.

Now, the events are received using MUIM_HandleEvent which is a method listed under MUI_Area. MUI_Window is not a sub class of MUI_Area, but the auto docs say this (see [here](http://www.sasg.com/mui/autodocs/MUI_Area.html#MUIM_HandleEvent) or [here](https://github.com/amiga-mui/muidev/wiki/MUI_Area#muim_handleevent)): _"This method is invoked whenever one of an event handler's trigger signals arrives. It's described in Area class context but does not really belong here"_.

Thus, on classic MUI using a window object as the receiving object works and has been in use, e.g. [here](https://sourceforge.net/p/muibase/code/HEAD/tree/trunk/src/amiga/mui/extclasses/ExtWindow_mcc.c#l282).

On AROS, however, the call to MUIM_HandleEvent is blocked by requiring the object to have the flags MADF_CANDRAW and MADF_SHOWME set (see [here](https://github.com/aros-development-team/AROS/blob/3b28655d041b42bcbf2526b1862fe2ca18b58cfe/workbench/libs/muimaster/classes/window.c#L1925-L1928)), which is not true for a window object.

This restriction does not match well to the intention that MUIM_HandleEvent can be used more broadly.  An easy fix is to remove the 4 code lines:

     if (!(_flags(ehn->ehn_Object) & MADF_CANDRAW))
        return 0;
    if (!(_flags(ehn->ehn_Object) & MADF_SHOWME))
        return 0;

With this change I get the same behavior as on classic MUI.

It is possible to work around this restriction by sending the events to an object of MUI_Area, e.g. the root object of the window, but it makes the code design more complicated.

**Comment by deadw00d** [comment]
I'm not that familiar with MUI. Do you know if it is possible to programatically trigger an event (so that an unit test case be written)?

**Comment by steffengutmann** [comment]
Here is a test case that I just built.  It relies on the fact that INTUITICKS are sent to the active window.  Results for i386-aros and m68k-amiga (UAE) are included.  I have also checked that if I do the proposed changes (commenting out the 4 lines), the test case passes.

[muim-handleevent.c.txt](https://github.com/deadw00d/AROS/files/7868696/muim-handleevent.c.txt)

**Comment by deadw00d** [comment]
Thank you very much!

**Comment by steffengutmann** [comment]
That's a good question.  I don't know if there is a good use case for MUI_Application (usually a single object) and MUI_Family (menu items).  All of the classes you mention are a sub class of MUI_Notify.  For some reasons the author of MUI decided to place MUIM_HandleEvent into the autodocs of MUI_Area although it seems MUI_Notify might have been a better place.

In the API there is no restriction on which objects are allowed for receiving events, thus I would think any object can receive them.  The only thing the object needs to do is handle the MUIM_HandleEvent method in the dispatcher.  I would think that any class can be allowed here.

**Comment by deadw00d** [comment]
I did a test with MUI_Notify under MUI3.8 and it seems it does not receive messages (although the window is not brought up in this case; if I change to rectangle it is brought up). Can you check if the code makes sense?

```
    ULONG sigs;
    Object *app = ApplicationObject, End;
    Object *obj = NewObject(mcc_Notify->mcc_Class, NULL, TAG_END);
    Object *win = WindowObject, MUIA_Window_RootObject, obj, End;
    DoMethod(app, OM_ADDMEMBER, win);

    struct MUI_EventHandlerNode ehnode;
    ehnode.ehn_Object = obj;
    ehnode.ehn_Class  = mcc_Notify->mcc_Class;
    ehnode.ehn_Events = IDCMP_INTUITICKS;
    ehnode.ehn_Priority = 10;
    DoMethod(win, MUIM_Window_AddEventHandler, &ehnode);

    set(win, MUIA_Window_Open, TRUE);

    numMessages = 0;

    for (int j = 0; j < 10; j++) {
        sigs = 0;
        do {
            DoMethod(app, MUIM_Application_NewInput, &sigs);
        } while (sigs == 0);
        Delay(1);
    }

    CU_ASSERT(numMessages == 0);

    DoMethod(win, MUIM_Window_RemEventHandler, &ehnode);
```

**Comment by steffengutmann** [comment]
If the window is not shown then it doesn't receive any IDCMP_INTUITICKS, and thus, no notification happens.

I believe MUIA_Window_RootObject must be an object of class MUI_Area (e.g. a RectangleObject).  Have you tried using a RectangleObject as the root object but still keeping the MUI_Notify object for receiving the events?

**Comment by deadw00d** [comment]
You are right - once the window is brought up, MUI_Notify object also received events. Thanks for pointing that out. This should complete test cases.
