### ISSUE TITLE
include file intuition.h member type xx_Class difference between struct DecoratorMessage and ScreenNotifyMessage

### ISSUE THREAD

**Issue by magorium** [deadw00d/AROS#66]
I was unable to locate any code that uses it, so please take it fwiw

When i was comparing some structure, i came along compiler/include/intuition/intuition.h

If i compare the members of the structures DecoratorMessage and ScreenNotifyMessage then i noticed that member dm_Class is declared as IPTR while snm_Class is declared as ULONG.

I suspect the latter (snm_Class) should be declared as IPTR as well ?

If not applicable then please feel free to close the issue without further action. I just wanted to have it mentioned somewhere, in case i run into it again and keep asking the same question.

**Comment by deadw00d** [comment]
Thanks for reporting. As far as I can see these two structures look similar but are not used in replaceable way. There is no need for them to have identical/aligned fields. Closing the ticket.
